### ISSUE TITLE
 Shows wrong temperature (Celsius)

### ISSUE THREAD

**Issue by thomasja27** [jmoor3/homeassistant-components#10]
Hi. 
Thank you very much for the job you have done, finally i got the tub in home assistant :)

But wonder one thing, does this component support celsius? 
Using the fork from plmilord: https://github.com/plmilord/Hass.io-custom-component-SpaClient/ 

My tub is showing 12 degrees celsius in the Balboa app and on the tub display, but in Home Assistant it shows -4,4 Celsius. 
If i change the unit to fahrenheit in Balboa app it shows 54 degrees there, but then the temperature is right in home assistant and shows 12 degrees celsius. 
Seems like there is something in the conversion that is not quite right.

**Comment by stringy92** [comment]
Hi, Just tried to the new release however I am having the same issue. 

When the hot tub is set to Fahrenheit the HA display shows - 38.2
When the hot tub is set to Celsius the HA display shows - 77

Hopefully Plmilord can help!

**Comment by plmilord** [comment]
This problem has been solved : [https://github.com/plmilord/Hass.io-custom-component-spaclient](url)

@thomasja27, you can close this issue….
