### ISSUE TITLE
Home Assistant 0.88 package issue

### ISSUE THREAD

**Issue by plmilord** [jmoor3/homeassistant-components#6]
Since updated to Home Assistant 0.88, I get these Error/Warning:

```
Log Details (ERROR)
Wed Feb 20 2019 20:00:33 GMT-0500 (heure normale de l’Est nord-américain)
Error loading custom_components.bullfrog.light. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 147, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ImportError: No module named 'custom_components.bullfrog.light'; 'custom_components.bullfrog' is not a package
```

```
Log Details (WARNING)
Wed Feb 20 2019 20:00:33 GMT-0500 (heure normale de l’Est nord-américain)
Integrations need to be in their own folder. Change light/bullfrog.py to bullfrog/light.py. This will stop working soon.
Extinction de "Spa Light".
```

The spa client program still working fine, but probably in a near update, we will get in trouble!

Any ideas?

**Comment by plmilord** [comment]
Ok… here is some info regarding "The Great Migration":
[https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html)

This explain why I get these Error/Warning but everything still working for now!

I will try to "package" the code!

**Comment by plmilord** [comment]
Ok, I found why I get these Error/Warning… "The Great Migration"!:
[https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html](https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html)

I will try to "package" the code!

**Comment by allanak** [comment]
Any plans to repackage this so it works in newer versions of hass?

**Comment by plmilord** [comment]
Have tried many things… but for now, nothing works properly. I will continue the work in good time and I will get back to you as soon as possible. Assume I'm new to Home Assistant architecture and in python!

I'm trying to follow these instructions...

https://community.home-assistant.io/t/0-89-breaking-change-prevent-partial-custom-component-overlays/103728/46

**Comment by plmilord** [comment]
I resolved the issue on homeassistant >0.89... Have a look to my Fork!

https://github.com/plmilord/homeassistant-components

What's different:
- 0.89 compliant (still need to work on a package)
- No more allusion to "bullfrog"
- No more allusion to "Mitsubishi MQTT"
- No more allusion to "ecobee"
- 1 toggle operation for pumps *may be an issue at this point for some spa owners. jmoor3's spa seems to work with two, mine work with only one!
- Code much more clean/lean
- Support 3 pumps

...I'm trying to merge jmoor3's master!

**Comment by plmilord** [comment]
Last update… I packed the custom component as requested to make it work properly in the near future.

...Merge to jmoor3's master project is still underway!

**Comment by stringy92** [comment]
@plmilord I am using this now, for HA 0.95.4 and the fahrenheit and celius isnt correct. It works as the opposite as to what is setup on the Balboa app

**Comment by plmilord** [comment]
Weird… Have you find why? On my side, my spa is set to display in farenheit, I use imperial display on my Home Assistant, and everything work fine! When I'm switching to metric display (celsius) on my Home Assistant, everything work fine too!

**Comment by jmoor3** [comment]
Thanks for taking the reins on this project @plmilord I have updated the readme to redirect people to your project since you've been keeping it up to date!
